export const todoTypes = {
    TODO_ADD: 'TODO_ADD',
    TODO_CHANGE: 'TODO_CHANGE',
    TODO_GET: 'TODO_GET',
    TODO_GET_COMPLETE: 'TODO_GET_COMPLETE',
    TODO_TOGGLE: 'TODO_TOGGLE'
}

export const filterTypes = {
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    SHOW_ALL: 'SHOW_ALL',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SHOW_COMPLETED: 'SHOW_COMPLETED'
}
